### ISSUE TITLE
Having users run unsafe commands is probably a bad idea

### ISSUE THREAD

**Issue by RandomSort** [praqma-training/docker-katas#56]
There must be a better way of breaking your container

**Comment by sofusalbertsen** [comment]
Is this regards to `rm -rf /` ?

**Comment by RandomSort** [comment]
Yes

Den 21. nov. 2017 13.03 skrev "Sofus Albertsen" <notifications@github.com>:

**Comment by tomhostyn** [comment]
Any command with side effects should illustrate the point.  E.g installing a benign tool like ping

`$ apt-get update && apt-get install iputils-ping -y
`
