### ISSUE TITLE
Add a cleaning up step

### ISSUE THREAD

**Issue by RandomSort** [praqma-training/docker-katas#57]
We know what images that are garbage after we have run through the exercises. We should have a simple description of how to clean up having done the exercises.

**Comment by sofusalbertsen** [comment]
Also, make all containers named, so that we can make `docker kill` commands in the cleanup step for each.

**Comment by OEHC** [comment]
If all containers are named `kata-[something]`, it will be easy to just stop/kill all containers with the `kata-` prefix, and afterwards run `docker system prune -a -f`.
But all the container names have to be unique. It is easy to give each command in the kata a unique name, but if the same command will be run again, the names will be conflicting.
A solution to this could be to to set the name to eg. `kata-5-nginx-$(pwgen 3 1)`. But this can easily clutter up the commands and make them look overly complicated I think.
