### ISSUE TITLE
Move all individual repositories to praqma-training organization in github

### ISSUE THREAD

**Issue by meekrosoft** [praqma-training/docker-katas#71]
Everyone in praqma should be able to update these example repo's

**Comment by Sharor** [comment]
Could you be a bit more specific what you mean @meekrosoft ? Is it not all in here or ?

**Comment by meekrosoft** [comment]
It seems there is only one...
https://github.com/praqma-training/docker-exercises/search?utf8=%E2%9C%93&q=sharor&type=

Maybe we could just switch the docs to use https://github.com/Praqma/helloworld

**Comment by Sharor** [comment]
It's a personal image of mine, and the exercise for linux dotnet even creates the exact same image :wink: Was just as an example. I dont think its super critical, and we can just use a Praqma image :slightly_smiling_face:

**Comment by sofusalbertsen** [comment]
@Sharor will you update/do this, or should I?

**Comment by Sharor** [comment]
I'll get to it when I get back from being sick 😉
